apiVersion: v1
kind: ConfigMap
metadata:
  name: ubby-mcp-api-config
  namespace: ubby
data:
  NODE_ENV: development
  PORT: "3000"
  MCP_DEFAULT_PORT: "3001"
  MCP_URL: "http://localhost:3001"
  MCP_USE_ANONYMIZED_TELEMETRY: "false"
  MCP_BASE_URL: https://{port}-ubby-mcp-api.soludev.tech
  BODY_SIZE_LIMIT: 10mb


