apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubby-mcp-api-ingress
  namespace: ubby
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-scheme: https
spec:
  rules:
    # API principale
    - host: ubby-mcp-api.soludev.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ubby-mcp-api
                port:
                  number: 3000