apiVersion: v1
kind: Service
metadata:
  name: ubby-mcp-api
  namespace: ubby
  labels:
    app: ubby-mcp-api
spec:
  type: ClusterIP
  selector:
    app: ubby-mcp-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http-3000
