apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-error-pages-front
  namespace: pickpro
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy-service
      port: 4180
    query: "/oauth2/sign_in?rd=https://pickpro.soludev.tech{url}"
