apiVersion: v1
kind: ConfigMap
metadata:
  name: pickpro-api-config
  namespace: pickpro
data:
  ALLOWED_ORIGINS: '["https://pickpro.soludev.tech"]'
  CHAT_MODEL: anthropic/claude-haiku-4.5
  TITLE_MODEL: anthropic/claude-haiku-4.5
  GRADER_MODEL: anthropic/claude-haiku-4.5
  TEMPERATURE: "0.0"
  CONCURRENT_CALLS: "20"
  OPEN_ROUTER_API_URL: https://openrouter.ai/api/v1
  PHOENIX_HOST: https://dev-phoenix.soludev.tech
  PYTHONPATH: ./pickpro_api



