apiVersion: v1
kind: ConfigMap
metadata:
  name: pickpro-api-config
  namespace: pickpro
data:
  ALLOWED_ORIGINS: '["https://pickpro.soludev.tech", "http://localhost:8080"]'
  DEV_MODE: "false"
  CHAT_MODEL: anthropic/claude-haiku-4.5
  TITLE_MODEL: anthropic/claude-haiku-4.5
  GRADER_MODEL: anthropic/claude-haiku-4.5
  JOB_STRUCTURE_MODEL: anthropic/claude-sonnet-4.5
  TEMPERATURE: "0.0"
  CONCURRENT_CALLS: "20"
  OPEN_ROUTER_API_URL: https://openrouter.ai/api/v1
  PHOENIX_HOST: https://phoenix.soludev.tech
  PYTHONPATH: ./pickpro_api
  MINIO_HOST: minio.pickpro.svc.cluster.local:9000
  MINIO_ACCESS: minioadmin
  MINIO_BUCKET: cvs
  MINIO_ALLOWED_EXTENSION: .pdf
  INDEXING_API_URL: http://pickpro-indexing-api.pickpro.svc.cluster.local:8000/pickpro/rest/v1


