apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpro-api
  namespace: pickpro
  labels:
    app: pickpro-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickpro-api
  template:
    metadata:
      labels:
        app: pickpro-api
    spec:
      containers:
        - name: pickpro-api
          image: kaiohz/pickpro:pickpro-back-c5c684830f0b6375e911a1f34eac42bb3100f0dd
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pickpro-api-config
            - secretRef:
                name: pickpro-api-secret
          livenessProbe:
            httpGet:
              path: /pickpro/rest/v1/health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pickpro/rest/v1/health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: pickpro-docker-secret
