apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openobserve-ingress
  namespace: soludev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-scheme: https
spec:
  rules:
    - host: dev-openobserve-minio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openobserve-openobserve-standalone
                port:
                  number: 5080