apiVersion: v1
kind: Service
metadata:
  name: soludev-landing
  namespace: soludev
  labels:
    app: soludev-landing
spec:
  type: ClusterIP
  selector:
    app: soludev-landing
  ports:
    - port: 5173
      targetPort: 80
      protocol: TCP
      name: http
