apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector
  namespace: ubby
  labels:
    app: pgvector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      tolerations:
        - key: "klipperlb-exclude"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
      volumes:
        - name: init-sql
          configMap:
            name: pgvector-init
        - name: pgvector-data
          persistentVolumeClaim:
            claimName: ubby-pgvector-pvc
      containers:
        - name: pgvector
          image: pgvector/pgvector:0.8.0-pg17
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pgvector-secret
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
            - name: pgvector-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "ubby", "-d", "ubby"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"