apiVersion: v1
kind: ConfigMap
metadata:
  name: ubby-back-config
  namespace: ubby
data:
  ALLOWED_ORIGINS: '["https://ubby.soludev.tech"]'
  HOST: 0.0.0.0
  PORT: "8000"
  UVICORN_LOG_LEVEL: info
  RELOAD: "true"
  MAX_WORKERS: "5"
  MAX_FILE_SIZE: "10485760"
  MCP_USE_API_URL: "https://ubby-mcp-api.soludev.tech/api/v1/mcp/create"


