# minio-values.yaml
# Namespace configuration
namespaceOverride: pickpro

mode: standalone
replicas: 1

rootUser: minioadmin
rootPassword: minioadmin

# Stockage
persistence:
  enabled: true
  existingClaim: minio
  storageClass: nfs-pickpro-minio
  accessMode: ReadWriteMany
  size: 5Gi

# Ressources
resources:
  requests:
    memory: 512Mi
    cpu: 250m

service:
  type: ClusterIP
  port: 9000

consoleService:
  type: ClusterIP
  port: 9001

# Cr√©er automatiquement le bucket CVs
buckets:
  - name: cvs
    policy: none