# minio-values.yaml
mode: standalone
replicas: 1

rootUser: minioadmin
rootPassword: minioadmin

# Stockage
persistence:
  enabled: true
  storageClass: nfs-cluster-global
  size: 5Gi

# Ressources
resources:
  requests:
    memory: 512Mi
    cpu: 250m

service:
  type: ClusterIP
  port: 9000

consoleService:
  type: ClusterIP
  port: 9001

# Cr√©er automatiquement le bucket CVs
buckets:
  - name: cvs
    policy: none