apiVersion: v1
kind: ConfigMap
metadata:
  name: pickpro-front-config
  namespace: pickpro
data:
  config.json: |
    {
        "logtoUrl": "https://dev-logto.soludev.tech",
        "logtoAppId": "0nvmupc3d9dfkxcd5zpip",
        "redirectUrl": "https://pickpro.soludev.tech/callback",
        "signOutUrl": "https://pickpro.soludev.tech/",
        "backendUrl": "https://pickpro-api.soludev.tech"
    }
