apiVersion: v1
kind: ConfigMap
metadata:
  name: pickpro-front-config
  namespace: pickpro
data:
  config.json: |
    {
        "backendUrl": "https://pickpro-api.soludev.tech",
        "oauth2ProxyUrl": "https://pickpro.soludev.tech",
        "logtoUrl": "https://dev-logto.soludev.tech"
    }
