apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pickpro-front-ingress
  namespace: prospectio
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-scheme: https
    traefik.ingress.kubernetes.io/custom-response-headers: Cache-Control:no-cache,no-store,must-revalidate||Pragma:no-cache||Expires:0
spec:
  rules:
    - host: pickpro.soludev.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pickpro-front
                port:
                  number: 5173