apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pickpro-front-ingress
  namespace: prospectio
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-scheme: https
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
      add_header Pragma "no-cache" always;
      add_header Expires "0" always;
spec:
  rules:
    - host: pickpro.soludev.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pickpro-front
                port:
                  number: 5173