server:
  # Utiliser le service account avec permissions TokenReview
  serviceAccount:
    create: false
    name: openbao
  tolerations:
    - key: klipperlb-exclude
      value: "true"
      effect: NoSchedule
      operator: Equal
  # Configuration du stockage NFS
  dataStorage:
    enabled: true
    size: 5Gi
    storageClass: nfs-soludev-openbao
    accessMode: ReadWriteMany