apiVersion: v1
kind: ConfigMap
metadata:
  name: ubby-front-config
  namespace: ubby
data:
  config.json: |
    {
      "apiBaseUrl": "http://localhost:8000/api/v1",
      "loginPageUrl": "http://localhost:3000/login"
    }
