apiVersion: v1
kind: Service
metadata:
  name: ubby-front
  namespace: ubby
  labels:
    app: ubby-front
spec:
  type: ClusterIP
  selector:
    app: ubby-front
  ports:
    - port: 4000
      targetPort: 80
      protocol: TCP
      name: http
