apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: soludev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-scheme: https
spec:
  rules:
    - host: dev-soludev-minio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: soludev-minio-console
                port:
                  number: 9001
    - host: dev-soludev-api-minio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: soludev-minio
                port:
                  number: 9000