apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: soludev-kustomization
  namespace: flux-system
spec:
  interval: 2m
  timeout: 90s
  wait: true
  targetNamespace: soludev
  sourceRef:
    kind: GitRepository
    name: kaiohz-repo
  path: "dev/soludev"
  #When the Git revision changes, the manifests are reconciled automatically. If previously applied objects are missing from the current revision, these objects are deleted from the cluster when spec.prune is enabled
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prospectio-kustomization
  namespace: flux-system
spec:
  interval: 2m
  timeout: 90s
  wait: true
  targetNamespace: prospectio
  sourceRef:
    kind: GitRepository
    name: kaiohz-repo
  path: "dev/prospectio"
  #When the Git revision changes, the manifests are reconciled automatically. If previously applied objects are missing from the current revision, these objects are deleted from the cluster when spec.prune is enabled
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pickpro-kustomization
  namespace: flux-system
spec:
  interval: 2m
  timeout: 90s
  wait: true
  targetNamespace: pickpro
  sourceRef:
    kind: GitRepository
    name: kaiohz-repo
  path: "dev/pickpro"
  #When the Git revision changes, the manifests are reconciled automatically. If previously applied objects are missing from the current revision, these objects are deleted from the cluster when spec.prune is enabled
  prune: true 
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubby-kustomization
  namespace: flux-system
spec:
  interval: 2m
  timeout: 90s
  wait: true
  targetNamespace: ubby
  sourceRef:
    kind: GitRepository
    name: kaiohz-repo
  path: "dev/ubby"
  #When the Git revision changes, the manifests are reconciled automatically. If previously applied objects are missing from the current revision, these objects are deleted from the cluster when spec.prune is enabled
  prune: true 



