postgresql:
  enabled: false

database:
  postgres:
    host: "postgres"
    port: 5432
    db: "phoenix"
    user: "phoenix"
    password: ""  # Password comes from external secret via additionalEnv

auth:
  enableAuth: true

#
additionalEnv:
  - name: PHOENIX_POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: soludev-phoenix-secret
        key: PHOENIX_POSTGRES_PASSWORD
  - name: PHOENIX_SECRET
    valueFrom:
      secretKeyRef:
        name: soludev-phoenix-secret
        key: PHOENIX_SECRET
  - name: PHOENIX_ADMIN_SECRET
    valueFrom:
      secretKeyRef:
        name: soludev-phoenix-secret
        key: PHOENIX_ADMIN_SECRET
  - name: PHOENIX_SMTP_PASSWORD
    valueFrom:
      secretKeyRef:
        name: soludev-phoenix-secret
        key: PHOENIX_SMTP_PASSWORD
  - name: PHOENIX_DEFAULT_ADMIN_INITIAL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: soludev-phoenix-secret
        key: PHOENIX_DEFAULT_ADMIN_INITIAL_PASSWORD

persistence:
  enabled: false

ingress:
  enabled: false

server:
  port: 6006