apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: soludev
data:
  config.yml: |
    tunnel: a67e25e7-bae5-4a2d-a46e-fc05d0c1f84e
    
    ingress:

      - hostname: soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: bao.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: logto.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: logto-admin.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: pickpro.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: pickpro-api.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: pickpro-indexing-api.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: openobserve.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: phoenix.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: headlamp.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: pickpro-oauth2-proxy.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: ubby.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: ubby-back.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: ubby-mcp-api.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: *.ubby-mcp-api.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: ubby-oauth2-proxy.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
      
      - service: http_status:404