apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: soludev
data:
  config.yml: |
    tunnel: a67e25e7-bae5-4a2d-a46e-fc05d0c1f84e
    
    ingress:
      - hostname: dev-bao.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: dev-logto.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: dev-logto-admin.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: pickpro.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: pickpro-api.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: dev-openobserve.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: dev-phoenix.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: dev-headlamp.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true

      - hostname: dev-oauth2-proxy.soludev.tech
        service: https://traefik.kube-system.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
      
      - service: http_status:404