config:
  existingSecret: "oauth2-proxy-credentials"
  existingConfig: "oauth2-proxy-config"
  cookieName: "oauth2-proxy"

sessionStorage:
  type: cookie

ingress:
  enabled: false

service:
  type: ClusterIP
  portNumber: 4180