apiVersion: v1
kind: ConfigMap
metadata:
  name: pickpro-indexing-api-config
  namespace: pickpro
data:
  ALLOWED_ORIGINS: '["https://pickpro.soludev.tech"]'
  INDEXING_MODEL: google/gemini-2.5-flash:nitro
  EMBEDDING_CLIENT: openai/text-embedding-3-large
  TEMPERATURE: "0.0"
  OPEN_ROUTER_API_URL: https://openrouter.ai/api/v1
  PYTHONPATH: ./pickpro_indexing_api
  MAX_WORKERS: "5"
  MINIO_HOST: minio.pickpro.svc.cluster.local:9000
  PHOENIX_HOST: https://phoenix.soludev.tech



