apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpro-indexing-api
  namespace: pickpro
  labels:
    app: pickpro-indexing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickpro-indexing-api
  template:
    metadata:
      labels:
        app: pickpro-indexing-api
    spec:
      containers:
        - name: pickpro-indexing-api
          image: kaiohz/pickpro:pickpro-indexing-api-6c3c2259436698bc6e35f796029ee56cfc580260
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pickpro-indexing-api-config
            - secretRef:
                name: pickpro-indexing-api-secret
          livenessProbe:
            httpGet:
              path: /pickpro/rest/v1/health/status
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pickpro/rest/v1/health/status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: pickpro-docker-secret
