apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpro-indexing-api
  namespace: pickpro
  labels:
    app: pickpro-indexing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickpro-indexing-api
  template:
    metadata:
      labels:
        app: pickpro-indexing-api
    spec:
      nodeSelector:
        type: standard
      tolerations:
        - key: "klipperlb-exclude"
          value: "true"
          effect: "NoSchedule"
          operator: "Equal"
      containers:
        - name: pickpro-indexing-api
          image: kaiohz/pickpro:pickpro-indexing-api-80277c4104bcd202de1dc81830829bbd21a170b3
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pickpro-indexing-api-config
            - secretRef:
                name: pickpro-indexing-api-secret
          livenessProbe:
            httpGet:
              path: /pickpro/rest/v1/health/status
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /pickpro/rest/v1/health/status
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "1500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
      imagePullSecrets:
        - name: pickpro-docker-secret
