apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pickpro-indexing-api-ingress
  namespace: pickpro
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: pickpro-traefik-forward-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/redirect-scheme: https
spec:
  rules:
    - host: pickpro-indexing-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pickpro-indexing-api
                port:
                  number: 8000