apiVersion: v1
kind: ConfigMap
metadata:
  name: logto-config
  namespace: soludev
data:
  TRUST_PROXY_HEADER: "true"
  ENDPOINT: "https://logto.soludev.tech"
  PORT: "3001"
  ADMIN_ENDPOINT: "https://logto-admin.soludev.tech"
  ADMIN_PORT: "3002"
  NODE_ENV: "production"