apiVersion: v1
kind: ConfigMap
metadata:
  name: logto-config
  namespace: soludev
data:
  TRUST_PROXY_HEADER: "1"
  ENDPOINT: "https://dev-logto.soludev.tech"
  ADMIN_ENDPOINT: "https://dev-logto-admin.soludev.tech"